### PR TITLE
Enable the example projects to use locally linked versions of the Vime packages

### PR DESCRIPTION
**Pull request by rossng**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Currently, it is not possible to use `npm link` or Lerna to use the local version of the `@vime/*` packages. There were a number of issues preventing this, all of which should be fixed by this PR.

The main motivation for this change is to make it possible to quickly test local changes to `@vime/core` without any ceremony.

Issue Number: N/A

## What is the new behavior?

- `examples/*` has been added to the Lerna workspaces, making it possible to bootstrap the `@vime/*` packages in these projects.
- `npm run build` has been changed to run only on the public packages (i.e. no `private: true`). This preserves the existing behaviour that examples will not be built during CI.
- A new `npm run bootstrap:all` command is introduced to allow bootstrapping the examples if desired.
- Documentation added for this behaviour
- A number of fixes required for the example projects:
  - `@vime/core`: copy the `icons/` folder structure correctly, so icons load when `NODE_ENV === development`.
  -  `@vime/react-example`: resolve `react` and `react-dom` correctly when using linked packages
  - `@vime/rollup-example`: update the CSS extension to make CSS generation work
  - `@vime/stencil-example`: fix icons not being found in dev mode
  - `@vime/webpack-example`: ensure Webpack always loads the extracted CSS
  - `@vime/angular-example`: preserve symlinks in Angular config

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by mihar-22** [comment]
Looks awesome to me. Not sure if this is related but getting some TS errors in CI? Seems unrelated to your changes though. Maybe we can patch in another PR. I also invited you to join the Vime organization so you can have more access. Let me know what you need. 

Thank you for the PR!

image

**Review by mihar-22 — APPROVED** [review]
LGTM

**Comment by mihar-22** [comment]
Feel free to merge once you've accepted invite. Just ping me for reviews on larger changes 😄

**Comment by rossng** [comment]
Just added another change to switch the Angular packages to the `v11-lts` tag - should avoid incompatible peer deps errors when using NPM 7.

**Comment by rossng** [comment]
After some fiddling CI seems to be working again 🙂.

I don't have write permissions on the repo, but probably best if you look over the last few commits anyway @mihar-22!

**Comment by mihar-22** [comment]
Awesome. **You have write access now.** The changes look good to me. It'd be nice if we didn't have to duplicate `.prettierignore` and instead extend `.gitignore` somehow? Either way fine with me.

**Comment by rossng** [comment]
I thought the same, but seems to be unsolved by Prettier so far: https://github.com/prettier/prettier/issues/8506

**Pull request merged**
