### PR TITLE
(feat): add cookies prop for vimeo provider

### PR DESCRIPTION
**Pull request by peacepostman**
## Feature - Add `cookies` prop for vimeo provider

This PR allow the use of the `dnt` parameter for vimeo ([documentation](https://vimeo.zendesk.com/hc/en-us/articles/360001494447-Using-Player-Parameters)).

The vimeo provider has now a new prop named `cookies`, which when turned to false, will prevent vimeo from tracking users.

I choose `cookies` in order to have the same interface used by youtube but i can perform changes if needed.

Best regards

### CODE REVIEW

**Comment by mihar-22** [comment]
This is awesome, thanks for the PR @peacepostman! I'll merge this in and release today after reviewing.

**Comment by peacepostman** [comment]
Hello @mihar-22, i know opensource is a second full time job ^^ but do you have any idea when you can validate the PR, i can use my fork to fill my needs but i would really like to stay on your git.

Have a nice day

**Comment by mihar-22** [comment]
Apologies @peacepostman for the delay, I had some other important work on my plate. Thanks for being understanding! I'll review now and if it looks good ship away 🚀

**Comment by mihar-22** [comment]
Oh one small issue... why was the `docs/package-lock.json` file deleted?

**Comment by peacepostman** [comment]
Oh sorry, it's a personal habit to never push it, i thought it shouldn't have been here. I update the PR right now.

**Comment by peacepostman** [comment]
Damn the process validation seems to fail. Do you have any idea why ?

**Comment by peacepostman** [comment]
If it is okay for you, i will create a brand new PR in order to prevent this issue, moreover, it will reduce the total commits ^^

**Pull request closed without merging**
